image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.build_template: &build_definition
  stage: build
  only:
    refs:
      - branches
      - /^v(?:\d+\.)+\d+$/
    variables:
      - $VARIANT_TAG
      - $VARIANT_TAG_WITH_VERSION
      - $VARIANT_BUILD_DIR
  except:
      refs:
        - master
  before_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Login to Docker Hub registry
  - echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin

  # Login to GitLab registry
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

  script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  - docker build
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:latest"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"
    -t "${CI_REGISTRY_IMAGE}:latest"
    "${VARIANT_BUILD_DIR}"

  - date '+%Y-%m-%d %H:%M:%S %z'

  # Push to Docker Hub registry. E.g. 'namespace/my-project:tag'
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:latest"

  # Push to GitLab registry. E.g. 'registry.gitlab.com/namespace/my-project:tag
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"
  - docker push "${CI_REGISTRY_IMAGE}:latest"

  after_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Log out of Docker Hub registry
  - docker logout

  # Log out of GitLab registry
  - docker logout "${CI_REGISTRY}"

build-cloudflare:
  <<: *build_definition
  variables:
    VARIANT_TAG: cloudflare
    VARIANT_TAG_WITH_VERSION: cloudflare-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/cloudflare

build-cloudxns:
  <<: *build_definition
  variables:
    VARIANT_TAG: cloudxns
    VARIANT_TAG_WITH_VERSION: cloudxns-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/cloudxns

build-digitalocean:
  <<: *build_definition
  variables:
    VARIANT_TAG: digitalocean
    VARIANT_TAG_WITH_VERSION: digitalocean-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/digitalocean

build-dnsimple:
  <<: *build_definition
  variables:
    VARIANT_TAG: dnsimple
    VARIANT_TAG_WITH_VERSION: dnsimple-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/dnsimple

build-dnsmadeeasy:
  <<: *build_definition
  variables:
    VARIANT_TAG: dnsmadeeasy
    VARIANT_TAG_WITH_VERSION: dnsmadeeasy-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/dnsmadeeasy

build-google:
  <<: *build_definition
  variables:
    VARIANT_TAG: google
    VARIANT_TAG_WITH_VERSION: google-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/google

build-linode:
  <<: *build_definition
  variables:
    VARIANT_TAG: linode
    VARIANT_TAG_WITH_VERSION: linode-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/linode

build-luadns:
  <<: *build_definition
  variables:
    VARIANT_TAG: luadns
    VARIANT_TAG_WITH_VERSION: luadns-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/luadns

build-nsone:
  <<: *build_definition
  variables:
    VARIANT_TAG: nsone
    VARIANT_TAG_WITH_VERSION: nsone-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/nsone

build-ovh:
  <<: *build_definition
  variables:
    VARIANT_TAG: ovh
    VARIANT_TAG_WITH_VERSION: ovh-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/ovh

build-rfc2136:
  <<: *build_definition
  variables:
    VARIANT_TAG: rfc2136
    VARIANT_TAG_WITH_VERSION: rfc2136-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/rfc2136

build-route53:
  <<: *build_definition
  variables:
    VARIANT_TAG: route53
    VARIANT_TAG_WITH_VERSION: route53-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/route53
